package com.school.vo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Product extends PageVo{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.title
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.picture
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.describes
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    private String describes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.uid
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.good_type_id
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    private Integer goodTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.flag
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.create_time
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd",timezone = "UTC+8")
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.title
     *
     * @return the value of goods.title
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.title
     *
     * @param title the value for goods.title
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.picture
     *
     * @return the value of goods.picture
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.picture
     *
     * @param picture the value for goods.picture
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.describes
     *
     * @return the value of goods.describes
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    public String getDescribes() {
        return describes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.describes
     *
     * @param describes the value for goods.describes
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    public void setDescribes(String describes) {
        this.describes = describes == null ? null : describes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.uid
     *
     * @return the value of goods.uid
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.uid
     *
     * @param uid the value for goods.uid
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.good_type_id
     *
     * @return the value of goods.good_type_id
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    public Integer getGoodTypeId() {
        return goodTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.good_type_id
     *
     * @param goodTypeId the value for goods.good_type_id
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    public void setGoodTypeId(Integer goodTypeId) {
        this.goodTypeId = goodTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.flag
     *
     * @return the value of goods.flag
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.flag
     *
     * @param flag the value for goods.flag
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.create_time
     *
     * @return the value of goods.create_time
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.create_time
     *
     * @param createTime the value for goods.create_time
     *
     * @mbggenerated Mon Feb 17 22:17:48 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}