package com.school.vo;

public class ProductType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_type.id
     *
     * @mbggenerated Wed Feb 19 22:06:00 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_type.good_type
     *
     * @mbggenerated Wed Feb 19 22:06:00 CST 2020
     */
    private String goodType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_type.id
     *
     * @return the value of good_type.id
     *
     * @mbggenerated Wed Feb 19 22:06:00 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_type.id
     *
     * @param id the value for good_type.id
     *
     * @mbggenerated Wed Feb 19 22:06:00 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_type.good_type
     *
     * @return the value of good_type.good_type
     *
     * @mbggenerated Wed Feb 19 22:06:00 CST 2020
     */
    public String getGoodType() {
        return goodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_type.good_type
     *
     * @param goodType the value for good_type.good_type
     *
     * @mbggenerated Wed Feb 19 22:06:00 CST 2020
     */
    public void setGoodType(String goodType) {
        this.goodType = goodType == null ? null : goodType.trim();
    }
}